# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = [""]
description = ""
language = "rust"
manifest_version = 3
name = "compute-service-with-ngwaf"
service_id = "dhx8oBr05CA9MZUqrbwfr4"

[local_server]

  [local_server.backends]

    [local_server.backends.httpme_origin]
    url = "https://http-me.glitch.me"

    [local_server.backends.status_origin]
    url = "https://status.demotool.site"

    [local_server.backends.ngwaf_origin]
    url = "https://compute-with-ngwaf-edge-vcl.global.ssl.fastly.net"
