# Service VCL variables
SERVICE_VCL_FRONTEND_DOMAIN_NAME = ""
SERVICE_VCL_BACKEND_HOSTNAME = ""

# Service Compute variables
SERVICE_COMPUTE_FRONTEND_DOMAIN_NAME = ""
SERVICE_COMPUTE_BACKEND_HOSTNAME = ""