# This file describes a Fastly Compute package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["brookscunningham@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-empty"
description = ""
language = "javascript"
manifest_version = 3
name = "service-compute"
service_id = ""

[scripts]
  build = "npm run build"
  post_init = "npm install"
