# Example YAML configuration for the sidecar pattern.
# https://docs.fastly.com/signalsciences/install-guides/kubernetes/kubernetes-reverse-proxy/

# How to Run Locally Built Docker Images in Kubernetes
# https://medium.com/swlh/how-to-run-locally-built-docker-images-in-kubernetes-b28fbc32cc1d


apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-controller-with-agent-lb
spec:
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  selector:
    app: nginx-ingress-controller-with-agent
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: '

  # load_module /etc/nginx/modules/ngx_http_sigsci_module.so;

  events {
  }
  http {
    server {
        listen 80;
        location / {
            proxy_set_header Host "http-me.glitch.me";
            proxy_pass http://httpme.glitch.me;
        }
        location /hello {
            return 200 "Hello world from nginx!\n";
        }
    }
  }
  '
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ingress-controller-with-agent
spec:
  selector:
    matchLabels:
      app: nginx-ingress-controller-with-agent
  template:
    metadata:
      labels:
        app: nginx-ingress-controller-with-agent
    spec:
      containers:
      - name: sigsci-agent
        image: signalsciences/sigsci-agent:latest
        imagePullPolicy: 
        env:
        - name: SIGSCI_ACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: ngwaf-agent-keys
              key: accesskeyid
        - name: SIGSCI_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: ngwaf-agent-keys
              key: secretaccesskey
        # - name: SIGSCI_REVPROXY_LISTENER
        #   value: "listen_conf:{listener=http://0.0.0.0:8080,upstreams=https://http-me.glitch.me:443,access-log='/dev/stdout',pass-host-header=false}"
        - name: SIGSCI_DEBUG_LOG_BLOCKED_REQUESTS
          value: "1"
        - name: SIGSCI_DEBUG_LOG_WEB_INPUTS
          value: "1"
        - name: SIGSCI_DEBUG_LOG_CONFIG_UPDATES
          value: "1"
        - name: SIGSCI_DEBUG_LOG_CONFIG_UPLOADS
          value: "1"
        - name: SIGSCI_DEBUG_LOG_WEB_OUTPUTS
          value: "1"
        volumeMounts:
        - name: sigsci-tmp
          mountPath: /sigsci/tmp

      - name: nginx
        # image: nginx:latest
        image: bcunningham/nginx-module
        imagePullPolicy: Never
        # Never pull the remote instance since this is built locally
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        # Shared mount with sigsci-agent container where the socket is shared via emptyDir volume
        - name: sigsci-tmp
          mountPath: /sigsci/tmp
      # restartPolicy: Never
      volumes:
        - name: sigsci-tmp
          emptyDir: {}

