# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = [""]
description = "Service chaining example"
language = "rust"
manifest_version = 2
name = "compute-service-chain"
service_id = ""

[local_server]

  [local_server.backends]

    [local_server.backends.my_origin_0]
      url = "https://httpbin.org"