controller:
    # Replaces the default nginx-controller image with a custom image that contains the Signal Sciences nginx Module
    image:
      repository: signalsciences/sigsci-nginx-ingress-controller
      tag: 1.10.0
      digest: false
      pullPolicy: IfNotPresent

    # Load module and set sigsci_agent_host
    config:
      main-snippet: load_module /usr/lib/nginx/modules/ngx_http_sigsci_module.so;
      http-snippet: sigsci_agent_host unix:/sigsci/tmp/sigsci.sock;

    # Loads sidecar Signal Sciences Agent
    extraContainers:
      - name: sigsci-agent
        image: signalsciences/sigsci-agent:latest
        volumeMounts:
        - name: sigsci-temp
          mountPath: /sigsci/tmp

        # Sets Signal Sciences Agent keys
        env:
        - name: SIGSCI_RPC_ADDRESS
          value: unix:/sigsci/tmp/sigsci.sock
        - name: SIGSCI_ACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: ngwaf-agent-config
              key:  accesskeyid
        - name: SIGSCI_SECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: ngwaf-agent-config
              key:  secretaccesskey
              

    # Mounts shared volume for sigsci.sock file
    extraVolumeMounts:
      - name: sigsci-temp
        mountPath: /sigsci/tmp

    extraVolumes:
      - name: sigsci-temp
        emptyDir: {}

# Originally from https://github.com/signalsciences/sigsci-nginx-ingress-controller/blob/main/sigsci-values.yaml
