# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["William Overton <will@fastly.com>"]
description = "An example of using geolocation for redirects"
language = "javascript"
manifest_version = 2
name = "GeoLocation"
service_id = "4QlfKtkOJ0dcRUQOFYp0cE"
